### ISSUE TITLE
Doesn't download second page of statements

### ISSUE THREAD

**Issue by simontong** [shuckster/OBIS#1]
In the Statements index when you hit the checkbox to retrieve specific month's statements it will only download the first page of transactions of that particular month.

New pages are generated after 201 transactions

**Comment by shuckster** [comment]
Sorry for that! I've never broken 100 transactions a month, so unfortunately I can't test this myself.

If you're willing, could you please send the plain HTML for both pages of a single-statement of yours? Obviously clear it of any personal information first.

**Comment by simontong** [comment]
I've pasted the HTML where the button exists. Also attached an image so you get a visual.

```
<div id="content" tabindex="0" class="main-content-wrapper clearfix dashboard ">
    <div id="portletWrapper">
        <div class="whiteBackground">
            <div class="extContentHighlightPib hsbcCol">
                <div class="extRowButton extPibRow hsbcRow">
                    <div class="extButtons">
                        <div class="hsbcButtonLeft"></div>
                        <div class="hsbcButtonCenter">
                            <a href="xxxx"
                               class="-arr"
                               title='Next page of this statement'>
                                Next page</a><i>.</i>
                        </div>
                        <div class="hsbcButtonRight"></div>
                    </div>
                </div>
                <div class="extRowButton extPibRow hsbcRow">
                    <div class="extButtons">
                        <div class="hsbcButtonLeft"></div>
                        <div class="hsbcButtonCenter">
                            <a href="xxxx"
                               class="hsbcButtonBack" title='Back to list of statements'>
                                Back to list
                            </a><i>.</i></div>
                        <div class="hsbcButtonRight"></div>
                        <div class="hsbcButtonLeft"></div>
                        <div class="hsbcButtonCenter">
                            <a href="xxxx"
                               class="-arr" target="_blank"
                               title='Download PDF.This link will open in a new browser window.'>
                                Download PDF
                                <span class="csHideForSR">A PDF of your statement will open in a new window</span>
                            </a><i>.</i>
                        </div>
                        <div class="hsbcButtonRight"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/1494859/22032036/b8ff0764-dcda-11e6-8cad-ac4fe14d52fe.png)

**Comment by shuckster** [comment]
Thanks for the feedback! Clear your browser-cache and give it another go. I'm not able to properly test it here, but hopefully progress has been made...

**Comment by shuckster** [comment]
I did one more tweak b3430894fbe13f803b2b41a8a7aca5330eea9bd0 this morning and it looks good to me. Let me know if it's working for you now.

**Comment by simontong** [comment]
Yup. looks like its working. Thanks!

**Comment by shuckster** [comment]
Super! Glad to hear it. :)

**Comment by shuckster** [comment]
I guess this might be a problem again since HSBC have updated their site?

**Comment by simontong** [comment]
Yup,

Looks like its not working anymore

**Comment by shuckster** [comment]
Did you try this from the Recent Transactions or Previous Statements page?

Does it still do the multi-page thing?

**Comment by simontong** [comment]
Both

**Comment by shuckster** [comment]
Okay. Well saving the source of the page no longer works, since it's auto-generated by the dojo JavaScript framework.

But if you can, for example, open the Elements tab in the Safari Developer Console. From there's it's possible copy parts or all of the DOM tree as text.

If you can paste something here for me to work with I'll try my best.

**Comment by shuckster** [comment]
Well this is embarrassing. I never did end up looking at this issue. 😬 

Needless to say, OBIS is completely rewritten and uses a different method for downloading statements, so I'll close this for now and wait for a future report on this.
